### ISSUE TITLE
代码阅读，请问下(size+1)^ size > size  什么情况下会成立？int size；

### ISSUE THREAD

**Issue by 1194451658** [cloudwu/pbc#116]
我怎么感觉只会<=

**Comment by starwing** [comment]
如果size是2^n-1这种bit pattern，也就是000...00111...11这种样子，假设有n个1，那么size+1就是n+1个1，异或的结果就是n+1个1，大于size（n个1）

**Comment by 1194451658** [comment]
多谢。好久没看C代码了，把^运算符理解错了:P。看明白了。

**Comment by 1194451658** [comment]
理解了
