### ISSUE TITLE
最新版skynet里调用报错

### ISSUE THREAD

**Issue by wlof202** [cloudwu/pbc#143]
[:01000015] lua loader error : error loading module 'protobuf.c' from file './luaclib/protobuf.so':
	./luaclib/protobuf.so: undefined symbol: lua_newuserdata

尝试把lua_newuserdata 改成lua_newuserdatauv,把lua的版本校验取消,
运行,直接爆内存了
求云大搞个lua54版呀

**Comment by cloudwu** [comment]
需包含同一版本的 lua.h 。

**Comment by liuxiang1992** [comment]
23/02/22 20:21:49.83 [:00000008] lua loader error : error loading module 'protobuf.c' from file './luaclib/protobuf.so':
	./luaclib/protobuf.so: undefined symbol: lua_newuserdata
stack traceback:
	[C]: in ?
	[C]: in upvalue 'require'
	./skynet/lualib/skynet/require.lua:31: in function 'require'
	./lualib/protobuf.lua:1: in main chunk
	[C]: in upvalue 'require'
	./skynet/lualib/skynet/require.lua:31: in function 'require'
	./service/main.lua:5: in local 'main'
	./skynet/lualib/loader.lua:50: in main chunk

**Comment by liuxiang1992** [comment]
> 需包含同一版本的 lua.h 。

我也有这个问题
23/02/22 20:21:49.83 [:00000008] lua loader error : error loading module 'protobuf.c' from file './luaclib/protobuf.so':
./luaclib/protobuf.so: undefined symbol: lua_newuserdata
stack traceback:
[C]: in ?
[C]: in upvalue 'require'
./skynet/lualib/skynet/require.lua:31: in function 'require'
./lualib/protobuf.lua:1: in main chunk
[C]: in upvalue 'require'
./skynet/lualib/skynet/require.lua:31: in function 'require'
./service/main.lua:5: in local 'main'
./skynet/lualib/loader.lua:50: in main chunk
