### ISSUE TITLE
import "MessageType.proto";报错.\parser.lua:53: syntax error at [Scene.proto] (8)

### ISSUE THREAD

**Issue by sigh667** [cloudwu/pbc#28]
testLogin.lua 文件内容如下：
require "protobuf"

t = parser.register("MessageType.proto","../../test/aa")
t = parser.register("Scene.proto","../../test/aa")

MessageType.proto 文件内容如下：
package com.proto.msg;
option java_package = "com.proto.msg.common";
option java_outer_classname = "MessageType";

enum CGMessageType{
    CG_START_MOVE = 851;
}

Scene.proto 文件内容如下：
package com.proto.msg.scene;
option java_package = "com.proto.msg.scene";
option java_outer_classname = "Scene";
import "MessageType.proto";

message CGStartMove {
    required int32 x = 1 ;
    required int32 y = 2 ;
}

我尝试了按顺序注册，但还是报错。如果打成一个pb文件的话，实战中某些pb文件会过大，不利于客户端动态更新

**Comment by softwareyangsong** [comment]
请问您是如何重新打包生成pb文件的，所有的proto文件都在同一个目录之下，打包生成的pb不带路径，也报跟您一样的错误。
