### ISSUE TITLE
protobuf.unpack 无法解析消息中嵌套的对象数组，但protobuf.decode可以成功

### ISSUE THREAD

**Issue by sigh667** [cloudwu/pbc#29]
将您的test.lua做了些微改动之后test.lua代码如下：
require "protobuf"

addr = io.open("../../build/addressbook.pb","rb")
buffer = addr:read "*a"
addr:close()
protobuf.register(buffer)

addressbook = {
    name = "Alice",
    id = 12345,
    phone = {
        { number = "1301234567" },
        { number = "87654321", type = "WORK" },
    }
}

code = protobuf.encode("tutorial.Person", addressbook)

decode = protobuf.decode("tutorial.Person" , code)

print(decode.name)
print(decode.id)
for _,v in ipairs(decode.phone) do
    print("\t"..v.number, v.type)
end

print("=========");
phonebuf = protobuf.pack("tutorial.Person.PhoneNumber number","87654321");
buffer = protobuf.pack("tutorial.Person name id phone", "Alice", 123, { phonebuf });
name,id,phone = protobuf.unpack("tutorial.Person name id phone", buffer);
print(name)
print(id)
for _,v in pairs(phone) do
    print(v.number, v.type)
end

输出结果如下：
Alice
12345
        1301234567      HOME
#         87654321      WORK

Alice
123
nil     nil

不知道为什么87654321      WORK会在这个网页上变粗体加大

**Comment by Angelatianwang** [comment]
嵌套怎么解析啊
