### ISSUE TITLE
Example of Lua binding with nested message?

### ISSUE THREAD

**Issue by shadylabs** [cloudwu/pbc#50]
Hi, Is it possible to include short example of using the lib from Lua for encoding / decoding nested messages? I mean when the message i have to encode has a field of type another message?
Thanks,
Plamen

**Comment by cloudwu** [comment]
https://github.com/cloudwu/pbc/blob/master/binding/lua/test.lua is the example.

message AddressBook is make up of several Person , and Person has the field phone with type PhoneNumber .

**Comment by shadylabs** [comment]
thanks
