### ISSUE TITLE
Using lua protobuf.so for iOS

### ISSUE THREAD

**Issue by deathemperor** [cloudwu/pbc#56]
I've been trying to make your protobuf working for iOS. At first I couldn't compile on Mac OS X but figured  it out by adding dynamic_lookup into CFLAGS. Think you could add this as an option for Mac OS X build

But when I loaded using protobuf.lua in my iOS game (running quick-cocos2dx which is lua) I got this error:

[LUA ERROR] error loading module 'protobuf.c' from file '/usr/local/lib/lua/5.1/protobuf.so':
	dlopen(/usr/local/lib/lua/5.1/protobuf.so, 2): no suitable image found.  Did find:
	/usr/local/lib/lua/5.1/protobuf.so: mach-o, but not built for iOS simulator

Any ideas?

**Comment by deathemperor** [comment]
I may use this wrongly (new to xcode and iOS) but how do I use pbc for quick-cocos2dx in XCode?

**Comment by xpol** [comment]
You should link `luaopen_protobuf_c` statically and do the follow.

~~~C++
static luaL_Reg modules[] = {
    {"protobuf.c", luaopen_protobuf_c},
    {NULL, NULL}
};

void preload_lua_modules(lua_State *L)
{
    // load extensions
    luaL_Reg* lib = modules;
    lua_getglobal(L, "package");
    lua_getfield(L, -1, "preload");
    for (; lib->func; lib++)
    {
        lua_pushcfunction(L, lib->func);
        lua_setfield(L, -2, lib->name);
    }
    lua_pop(L, 2);
}
~~~

and call `preload_lua_modules` after create lua state.

**Comment by xpol** [comment]
Your error is nothing to do with pbc at all.
Its how Lua load statically linked module.

**Comment by deathemperor** [comment]
thanks I got it working with XCode
