### ISSUE TITLE
lua/pbc-lua.c windows下编译问题

### ISSUE THREAD

**Issue by luzexi** [cloudwu/pbc#66]
由于windows下编译不通过，查看原因。

https://github.com/cloudwu/pbc/blob/master/binding/lua/pbc-lua.c

``` c
#ifndef _MSC_VER
#include <alloca.h>
#else
#define alloca _alloca
#endif
```

是否应该改成

``` c
#ifndef WINVER
#include <alloca.h>
#else
#define alloca _alloca
#endif
```

在用MinGW编译pbc与slua合进dll时发生的错误。

**Comment by luzexi** [comment]
不改报找不到alloca.h，改掉，或者全部删掉，就可以。

**Comment by dearlulu** [comment]
I also met the question.
Do you have some enlighten effect on solving this question?

**Comment by owt5008137** [comment]
https://github.com/cloudwu/pbc/pull/80
这个PR修复了这个问题。让lua53和lua51保持一致
