### ISSUE TITLE
luajit 2.1 test failed

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/pbc#70]
@CheyiLin 

Could you update to luajit 2.1 ? It failed today.

https://travis-ci.org/cloudwu/pbc/jobs/105082547

**Comment by CheyiLin** [comment]
OK I found the problem: LuaJIT 2.1 `beta1` released (from `alpha`) and the standalone interpreter renamed from `luajit-2.1.0-alpha` to `luajit-2.1.0-beta1`.

I'll send a PR as soon as possible.
