### ISSUE TITLE
空数组共享地址的问题

### ISSUE THREAD

**Issue by ZhouWeikuan** [cloudwu/pbc#75]
定义一个消息结构:
package Test;

// 每一手牌
message CardInfo {
    optional int32   seatId     = 1;
    repeated int32   cards      = 2;
}

message SeatInfo {
    optional int32 seatId       = 2;

    repeated CardInfo histCards = 5;
}

message GameInfo {
    optional int32    curSeatId     = 6;

    repeated SeatInfo   seatInfo    = 10; // playingUsers
}

执行以下代码：
    local protobuf = require "protobuf"
    protobuf.register_file("protos/Test.pb")
    local gameInfo = {}
    gameInfo.seatInfo = {}
    for i=1,4 do
        local one = {}
        gameInfo.seatInfo[i] = one
        one.seatId = i

        local b = {}

        --[[
        b[1] = {}
        b[1].seatId = i
        b[1].cards = {}
        --]]

        one.histCards = b
    end

    local msg = protobuf.encode("Test.GameInfo", gameInfo)
    gameInfo  = protobuf.decode("Test.GameInfo", msg)
    for i=1,4 do
        print("histCards for ", i, " is ", tostring(gameInfo.seatInfo[i].histCards))
    end

发现所有的histCards都指向同一个地址，把一个元素加到数组里，操作了一个，就会影响所有的histCards:
histCards for   1        is     table: 0x2b8fc19b4e80
histCards for   2        is     table: 0x2b8fc19b4e80
histCards for   3        is     table: 0x2b8fc19b4e80
histCards for   4        is     table: 0x2b8fc19b4e80

如果把代码里注释打开，histCards不是空数组，就不会共享地址里。
所以猜测所有的空数组都共享一个空表，如果对这个空表改动，所有别的包里的空数组都有问题了

**Comment by cloudwu** [comment]
这是个特性。

如果你不需要，那么对 decode 出来的数据做一次深拷贝再使用。

**Comment by ZhouWeikuan** [comment]
如果要保护的话，为甚么不加个写保护，防止被误用？

**Comment by cloudwu** [comment]
你可以自己加上。我不想再跟进这个项目。

**Comment by ZhouWeikuan** [comment]
好吧，不过现在还没有这个能力和时间加...

**Comment by ZhouWeikuan** [comment]
那pbc里解析传过来的空表，被优化成nil, pairs时遍历不到，这个也是特性了？

**Comment by ZhouWeikuan** [comment]
另外，想不太通pbc延迟解析的好处。经过我们的使用，目前延迟解析至少有这几个问题:
1) 解析出的表无法跨服务使用，必须extract后才能跨服务;
2) 这个issue所说的空表共享的问题，这样每次解析后必须deep copyTable才能写入; 性能上也不比完全解析然后可写可读好多少?

所以，能分享一下pbc延迟解析的好处吗？
