### ISSUE TITLE
pbc使用问题

### ISSUE THREAD

**Issue by nanmuyao** [cloudwu/pbc#90]
云风大大，本人小白参考网上文章在cocos2dx中集成了您的pdc，但是我使用过程中遇到一个问题，因为
lua是弱类型语言，在用socket和服务器通信的过程中我们要有一个socket包头，然后包头第一个数据是一个
int类型数据代表包的长度，现在使用的游戏引擎内嵌的是lua5.1版本没有办法支持lpack，所已想问下可以用
pbc生成一个int类型数据嗎？类似于 local strLen = pbc:writeInt(I,"4") print("strlen",strlen) : 4(int).多谢云风大大指教

**Comment by BoyYaoHe** [comment]
自己集成lpack

**Comment by nanmuyao** [comment]
好吧，这me久了竟然有人回复，多谢
