### ISSUE TITLE
macos下编译binding lua53错误。

### ISSUE THREAD

**Issue by feihuroger** [cloudwu/pbc#97]
macos 10.12
brew安装的 lua53， protobuf （3.3.2）
编译 pbc是没有问题的，只是测试test的时候，提示
Please use 'syntax = "proto2";' or 'syntax = "proto3";' 而已
编译binding/lua53的时候，Makefile文件已经修改了 lua53的 include路径

gcc -O2 -fPIC -Wall -shared -o protobuf.so -I../.. -I/usr/local/Cellar/lua53/5.3.1_1/include/lua5.3 -L../../build pbc-lua53.c -lpbc
Undefined symbols for architecture x86_64:
  "_luaL_buffinit", referenced from:
      __pattern_pack in pbc-lua53-608caf.o
  "_luaL_checkinteger", referenced from:
      __rmessage_new in pbc-lua53-608caf.o
      __rmessage_int in pbc-lua53-608caf.o
      __rmessage_real in pbc-lua53-608caf.o
      __pattern_unpack in pbc-lua53-608caf.o
      __pattern_pack in pbc-lua53-608caf.o
      __decode in pbc-lua53-608caf.o
。。。。。。
。。。。。。
。。。。。。（类似错误提示）
  "_lua_type", referenced from:
      __env_type in pbc-lua53-bd02ca.o
      __pattern_pack in pbc-lua53-bd02ca.o
      __decode in pbc-lua53-bd02ca.o
      _decode_cb in pbc-lua53-bd02ca.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [protobuf.so] Error 1

有点方，搜索了一些，没找到合适的解决。难道是编译pbc的时候需要？

**Comment by feihuroger** [comment]
安装了 protobuf@2.5， 没有解决这个问题。

**Comment by zhongfq** [comment]
如果是mac编译protobuf，好像是要加上-bundle -undefined dynamic_lookup选项的

**Comment by feihuroger** [comment]
群里广州O也给了这个提示，自己测试，加上：  -undefined dynamic_lookup
就可以编译通过了。 -bundle不行。 
CFLAGS = -O2 -fPIC -Wall -undefined dynamic_lookup 
不管怎样，OK了。谢谢各位

**Comment by iosliujun** [comment]
测试加上-undefined dynamic_lookup 去掉-shared 有效

**Comment by imageslr** [comment]
大赞，编译 protobuf c++ helloworld 不成功，执行 `g++` 的时候加上 `-undefined dynamic_lookup` 就可以了。
全网唯一有用的回答。
